community:
  links:
    slack:
      label: "Slack"
      url: "https://clickhouse.com/slack"
      description: "allows chatting with ClickHouse users in real-time."
    telegram:
      label: "Telegram"
      url: "https://telegram.me/clickhouse_en"
      description: "allows chatting with ClickHouse users in real-time."
    youtube:
      label: "YouTube channel"
      url: "https://www.youtube.com/c/ClickHouseDB"
      description: "has a lot of content about ClickHouse in video format."
    blog:
      label: "Blog"
      url: "https://clickhouse.com/blog/"
      description: "contains various ClickHouse-related articles, as well as announcements and reports about events."
    bluesky:
      label: "Bluesky"
      url: "https://bsky.app/profile/clickhouse.com"
      description: "is a good place for short news."
    x:
      label: "X"
      url: "https://x.com/ClickHouseDB"
      description: "is a good place for short news."
release:
  version: "26.6"
  date: "2026-06-24"
  call_url: "https://clickhouse.com/company/news-events"
  theater_url: "https://presentations.clickhouse.com/"
  youtube_playlist_url: "https://www.youtube.com/playlist?list=PL0Z2YDlm0b3jAlSy1JxyP8zluvXaN3nxU"
  badge_style: "for-the-badge"
