# Community Configuration for ClickHouse

release:
  next_date: "2026-06-21"
  version: "26.6"
  event_url: "https://clickhouse.com/company/events/v26-6-community-release-call"

community_links:
  slack:
    name: Slack
    url: "https://clickhouse.com/slack"
  telegram:
    name: Telegram
    url: "https://telegram.me/clickhouse_en"
  youtube:
    name: YouTube
    url: "https://www.youtube.com/c/ClickHouseDB"
  blog:
    name: Blog
    url: "https://clickhouse.com/blog/"
  bluesky:
    name: Bluesky
    url: "https://bsky.app/profile/clickhouse.com"
  x:
    name: X (Twitter)
    url: "https://x.com/ClickHouseDB"

official_links:
  website:
    name: Official website
    url: "https://clickhouse.com/"
  cloud:
    name: ClickHouse Cloud
    url: "https://clickhouse.cloud"
  tutorial:
    name: Tutorial
    url: "https://clickhouse.com/docs/getting_started/tutorial/"
  documentation:
    name: Documentation
    url: "https://clickhouse.com/docs/"
  theater:
    name: ClickHouse Theater
    url: "https://presentations.clickhouse.com/"
  contacts:
    name: Contacts
    url: "https://clickhouse.com/company/contact"
  careers:
    name: Careers
    url: "https://clickhouse.com/company/careers"
